// Placeholder data — replace with real DB queries when content is ready

export const MOCK_RECIPES = [
  {
    id: '1',
    slug: 'crispy-carnitas-tacos',
    title: 'Crispy Carnitas Tacos',
    description: 'Slow-braised pork shoulder crisped in its own fat, served on warm corn tortillas with pickled onions and salsa verde.',
    heroImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
    prepTime: 20,
    cookTime: 240,
    servings: 6,
    difficulty: 'MEDIUM',
    cuisine: 'Mexican',
    category: 'Mains',
    tags: ['pork', 'tacos', 'mexican', 'slow-cook'],
    isSubscriber: false,
    isFeatured: true,
    rating: 4.9,
    commentCount: 47,
    likeCount: 312,
  },
  {
    id: '2',
    slug: 'saffron-risotto',
    title: 'Saffron Risotto alla Milanese',
    description: 'Silky, golden risotto made with Carnaroli rice, real saffron, dry white wine, and a cloud of Parmigiano Reggiano.',
    heroImage: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80',
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'HARD',
    cuisine: 'Italian',
    category: 'Mains',
    tags: ['italian', 'rice', 'vegetarian', 'date-night'],
    isSubscriber: true,
    isFeatured: true,
    rating: 4.8,
    commentCount: 29,
    likeCount: 198,
  },
  {
    id: '3',
    slug: 'smash-burgers',
    title: 'Perfect Smash Burgers',
    description: 'Double smash patties, American cheese, caramelized onions, and secret sauce on a toasted brioche bun.',
    heroImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'EASY',
    cuisine: 'American',
    category: 'Mains',
    tags: ['beef', 'burger', 'quick', 'weekend'],
    isSubscriber: false,
    isFeatured: false,
    rating: 5.0,
    commentCount: 83,
    likeCount: 547,
  },
  {
    id: '4',
    slug: 'miso-glazed-salmon',
    title: 'Miso-Glazed Salmon',
    description: 'Broiled salmon with a caramelized white miso glaze, served with sesame green beans and steamed rice.',
    heroImage: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80',
    prepTime: 15,
    cookTime: 12,
    servings: 2,
    difficulty: 'EASY',
    cuisine: 'Japanese-inspired',
    category: 'Seafood',
    tags: ['fish', 'healthy', 'quick', 'japanese'],
    isSubscriber: false,
    isFeatured: true,
    rating: 4.7,
    commentCount: 61,
    likeCount: 284,
  },
  {
    id: '5',
    slug: 'sourdough-bread',
    title: 'Open-Crumb Sourdough',
    description: 'A detailed guide to baking bakery-quality sourdough at home — scoring, steam, and that perfect ear.',
    heroImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    prepTime: 60,
    cookTime: 45,
    servings: 1,
    difficulty: 'HARD',
    cuisine: 'French',
    category: 'Baking',
    tags: ['bread', 'sourdough', 'baking', 'fermentation'],
    isSubscriber: true,
    isFeatured: false,
    rating: 4.9,
    commentCount: 112,
    likeCount: 891,
  },
  {
    id: '6',
    slug: 'burnt-basque-cheesecake',
    title: 'Burnt Basque Cheesecake',
    description: 'Intentionally torched, crustless cheesecake with a molten center and silky texture. 5 ingredients.',
    heroImage: 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=800&q=80',
    prepTime: 10,
    cookTime: 60,
    servings: 8,
    difficulty: 'EASY',
    cuisine: 'Spanish',
    category: 'Desserts',
    tags: ['dessert', 'cheese', 'baking', 'spanish'],
    isSubscriber: false,
    isFeatured: false,
    rating: 4.8,
    commentCount: 44,
    likeCount: 372,
  },
]

export const MOCK_PRODUCTS = [
  {
    id: '1',
    slug: 'provecho-canvas-apron',
    name: 'Provecho Canvas Apron',
    description: 'Heavy-duty waxed canvas apron with genuine leather straps, a front pocket, and a bottle opener loop. Built to outlast your cooking obsession.',
    heroImage: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    category: 'APPAREL',
    isFeatured: true,
    variants: [
      { id: '1a', name: 'Natural / One Size', sku: 'APR-NAT-OS', price: 8900, stock: 24, color: 'Natural' },
      { id: '1b', name: 'Black / One Size',   sku: 'APR-BLK-OS', price: 8900, stock: 12, color: 'Black' },
    ],
  },
  {
    id: '2',
    slug: 'provecho-chef-tee',
    name: 'Chef Tee — Heavy Cotton',
    description: '7 oz ring-spun cotton, relaxed fit. "Provecho" embroidered chest logo. Washes beautifully, keeps its shape.',
    heroImage: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    ],
    category: 'APPAREL',
    isFeatured: true,
    variants: [
      { id: '2a', name: 'White / S',  sku: 'TEE-WHT-S',  price: 4200, stock: 30, size: 'S',  color: 'White' },
      { id: '2b', name: 'White / M',  sku: 'TEE-WHT-M',  price: 4200, stock: 45, size: 'M',  color: 'White' },
      { id: '2c', name: 'White / L',  sku: 'TEE-WHT-L',  price: 4200, stock: 38, size: 'L',  color: 'White' },
      { id: '2d', name: 'White / XL', sku: 'TEE-WHT-XL', price: 4200, stock: 20, size: 'XL', color: 'White' },
      { id: '2e', name: 'Black / S',  sku: 'TEE-BLK-S',  price: 4200, stock: 18, size: 'S',  color: 'Black' },
      { id: '2f', name: 'Black / M',  sku: 'TEE-BLK-M',  price: 4200, stock: 22, size: 'M',  color: 'Black' },
      { id: '2g', name: 'Black / L',  sku: 'TEE-BLK-L',  price: 4200, stock: 15, size: 'L',  color: 'Black' },
      { id: '2h', name: 'Black / XL', sku: 'TEE-BLK-XL', price: 4200, stock: 9,  size: 'XL', color: 'Black' },
    ],
  },
  {
    id: '3',
    slug: 'carbon-steel-skillet-10in',
    name: 'Carbon Steel Skillet 10"',
    description: 'Pre-seasoned carbon steel skillet that bridges cast iron and stainless. Screaming-hot sears, oven-safe to 700°F, and feather-light compared to cast iron.',
    heroImage: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    category: 'COOKWARE',
    isFeatured: true,
    variants: [
      { id: '3a', name: '10" / Black', sku: 'PAN-CS-10', price: 13500, stock: 16, color: 'Black' },
    ],
  },
  {
    id: '4',
    slug: 'spice-collection',
    name: 'Provecho Spice Collection',
    description: 'Our 6-jar curated spice set — the exact blends we use on the channel. Custom-ground weekly, shipped fresh.',
    heroImage: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800&q=80',
    ],
    category: 'ACCESSORIES',
    isFeatured: false,
    variants: [
      { id: '4a', name: 'Set of 6', sku: 'SPICE-6SET', price: 5400, stock: 40 },
    ],
  },
]

export const MOCK_SOCIAL_POSTS = [
  {
    id: '1',
    platform: 'instagram' as const,
    thumbnail: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80',
    caption: 'Carnitas taco night 🌮 Recipe link in bio',
    url: 'https://instagram.com',
    likes: 2341,
    videoUrl: null,
  },
  {
    id: '2',
    platform: 'youtube' as const,
    thumbnail: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&q=80',
    caption: 'Perfect Saffron Risotto — start to finish',
    url: 'https://youtube.com',
    views: 184000,
    duration: '14:32',
  },
  {
    id: '3',
    platform: 'instagram' as const,
    thumbnail: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    caption: 'The smash burger that broke my kitchen',
    url: 'https://instagram.com',
    likes: 5892,
    videoUrl: null,
  },
  {
    id: '4',
    platform: 'youtube' as const,
    thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    caption: 'Sourdough masterclass — everything I know',
    url: 'https://youtube.com',
    views: 312000,
    duration: '28:14',
  },
  {
    id: '5',
    platform: 'instagram' as const,
    thumbnail: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80',
    caption: 'Miso salmon in 12 minutes flat ✨',
    url: 'https://instagram.com',
    likes: 3107,
    videoUrl: null,
  },
  {
    id: '6',
    platform: 'youtube' as const,
    thumbnail: 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=600&q=80',
    caption: 'Basque cheesecake — the ONLY dessert recipe you need',
    url: 'https://youtube.com',
    views: 97000,
    duration: '9:48',
  },
]
